### ISSUE TITLE
General information about ismir and conferences: attendance, nb of submissions, acceptance rate, etc.

### ISSUE THREAD

**Issue by emiliagogu** [ismir-net/ismir_web#10]
It would be nice to include some information about ismir and its impact. One good example is found at the ismir2015 website (number of submissions, impact of ismir) that should be updated and could be complemented with some statistics on the mailing list (geographical location, number of subscribers, etc). 
 http://ismir2015.uma.es/aboutismir.html http://ismir2015.uma.es/ismirimpact.html

**Comment by emiliagogu** [comment]
Also at ismir 2016 website https://wp.nyu.edu/ismir2016/about/about-ismir/

**Comment by woodshop** [comment]
Fixed with commit 7c865a1b9922cafe1c973a86cdf5130f0e24e755
