### ISSUE TITLE
Affiliation Meinard Müller

### ISSUE THREAD

**Issue by stefan-balke** [ismir-net/ismir_web#11]
Hi, 

just a minor thing:
https://github.com/ismir-net/ismir_web/blob/master/society.html#L82

should be:
Member-at-large: Meinard Müller, **International Audio Laboratories Erlangen**, Germany

Best
Stefan

**Comment by ehumphrey85** [comment]
awesome, thx -- willfix

**Comment by ejhumphrey** [comment]
awesome, thx -- willfix

**Comment by stefan-balke** [comment]
Oh, and also.
Frans Weiring, Universiteit Utrecht, The Netherlands

should be
Frans **Wiering**, Universiteit Utrecht, The Netherlands
http://www.uu.nl/medewerkers/FWiering

Thanks.

**Comment by ejhumphrey** [comment]
derp. thanks!
