### ISSUE TITLE
Update bylaws PDF

### ISSUE THREAD

**Issue by ehumphrey85** [ismir-net/ismir_web#12]

**Comment by woodshop** [comment]
Didn't catch exactly what's involved here. I see that the wording on the docs on Google drive and the website are the same, with different fonts. Am I simply replacing the document, or am I updating the document to reflect all the current board positions? Thanks!

**Comment by woodshop** [comment]
The old and current by-laws have been committed to the repo. The current repo has been synced to the live website.
